---


- name: Install libgdal
  apt: name={{ item }} state=latest
  with_items:
    - libgdal-dev


- name: Install giscube admin
  include_role:
    name: giscube-uwsgi-app
  vars:
    APP_DEBUG: False
    APP_NAME: giscube
    APP_PATH: "{{ giscube_apps_path }}/giscube"
    APP_URL: "{{ giscube_admin_app_url }}"
    APP_GIT_URL: "https://github.com/giscube/giscube-admin.git"
    APP_DEPLOY_USER: "{{ giscube_admin_deploy_user | default('www-data') }}"
    # APP_CODE_PATH: /devel/giscube/admin/giscube-admin/
    APP_REQUIREMENTS: "requirements{{ ( ansible_distribution_version | version_compare('17.10', '>=') )|ternary('-gdal2', '')}}.txt"

    APP_DB_CREATE: False
    APP_DB_HOST: "{{ giscube_admin_db_host | default('localhost') }}"
    APP_DB_NAME: "{{ giscube_admin_db_name | default('giscube') }}"
    APP_DB_USER: "{{ giscube_admin_db_user | default('giscube') }}"
    APP_DB_PASSWORD: "{{ giscube_admin_db_password }}"
    APP_DB_POSTGIS: True

    APP_ALLOWED_HOSTS: "{{ giscube_admin_host }}"
    APP_LANGUAGE_CODE: "{{ giscube_admin_language }}"
    APP_SECRET_KEY: "{{ giscube_admin_secret_key }}"
    APP_PYTHON3: False
    APP_UWSGI_OLD: False
    APP_UWSGI_ONDEMAND: False
    APP_USE_CAS: False
    APP_UWSGI_MODULE: giscube/wsgi.py
    APP_DISABLE_SSL: False
    APP_EXTRA_VARS: {
        MEDIA_ROOT: "{{ giscube_admin_media_path }}",
        GISCUBE_GIS_SERVER_ENABLED: True,
        GISCUBE_GIS_SERVER_URL: "{{ giscube_admin_http_host }}/fcgis/giscube_qgisserver",
        GISCUBE_IMAGE_SERVER_ENABLED: False,
        VAR_ROOT: "{{ giscube_apps_path }}/giscube/var/",
        GISCUBE_URL: "{{ giscube_admin_http_host }}{{ giscube_admin_app_url }}"
    }
    UWSGI_EXTRA_VARS: {
        workers: 1,
        threads: 8
    }
  environment:
      CPLUS_INCLUDE_PATH: /usr/include/gdal
      C_INCLUDE_PATH: /usr/include/gdal
      GISCUBE_IMAGE_SERVER_ENABLED: "{{ giscube_admin_image_server_enabled | default('false') }}"
      GISCUBE_GIS_SERVER_ENABLED: "{{ giscube_admin_gis_server_enabled | default('false') }}"
      GISCUBE_GEOPORTAL_ENABLED: "{{ giscube_admin_geoportal_server_enabled | default('false') }}"


- name: Create media/ directory
  file:
      path="{{ giscube_admin_media_path }}"
      state=directory
      mode=755
      owner=www-data
      group=www-data
